"""Learning response contract."""

from dataclasses import dataclass
from typing import Any


@dataclass(slots=True)
class LearningResponse:
    """Response generated by learning pipeline."""

    success: bool
    result: Any = None
    message: str = ""