from dataclasses import dataclass, field
from typing import Any, Dict, List


@dataclass
class MemoryResponse:
    """
    Represents a response generated by
    the memory subsystem.
    """

    success: bool

    message: str = ""

    memories: List[Any] = field(
        default_factory=list
    )

    metadata: Dict = field(
        default_factory=dict
    )