from dataclasses import dataclass

from ..domain.adaptation_result import AdaptationResult


@dataclass
class AdaptationResponse:
    """
    Response generated by the adaptation capability.
    """

    result: AdaptationResult