from typing import Optional

from src.agents.planning.execution_plan import ExecutionPlan
from src.agents.planning.plan_step import PlanStep
from src.agents.planning.planner_strategy import PlannerStrategy
from src.agents.reasoning.reasoning_result import ReasoningResult


class DynamicExecutionPlanner:
    """
    Creates dynamic execution plans
    based on user intent analysis.

    In V1.11 the planner can consume
    reasoning information generated by
    the ReasoningEngine.
    """

    def __init__(
        self,
        strategy=None
    ):

        self.strategy = (
            strategy
            if strategy
            else PlannerStrategy()
        )


    def create_plan(
        self,
        question: str,
        reasoning_result: Optional[ReasoningResult] = None
    ) -> ExecutionPlan:
        """
        Create execution plan based
        on intent analysis and optional
        reasoning information.
        """


        analysis = (
            self.strategy.analyze(
                question
            )
        )


        request_type = (
            analysis.get(
                "type",
                "unknown"
            )
        )


        steps = [

            PlanStep(
                step_id=1,
                description="Route user request",
                action="route_request"
            ),

            PlanStep(
                step_id=2,
                description=(
                    f"Execute {request_type} operation"
                ),
                action="execute_tool"
            ),

            PlanStep(
                step_id=3,
                description="Generate final response",
                action="generate_response"
            )

        ]


        plan = ExecutionPlan(
            objective=question,
            steps=steps
        )


        if reasoning_result:

            plan.metadata = {

                "reasoning": (
                    reasoning_result.reasoning
                ),

                "conclusion": (
                    reasoning_result.conclusion
                ),

                "confidence": (
                    reasoning_result.confidence
                ),

                "strategy": (
                    reasoning_result.strategy
                    if hasattr(
                        reasoning_result,
                        "strategy"
                    )
                    else "default"
                ),

                "required_capabilities": (
                    reasoning_result.required_capabilities
                    if hasattr(
                        reasoning_result,
                        "required_capabilities"
                    )
                    else []
                )

            }


        return plan