from typing import List, Optional, Dict, Any

from src.agents.planning.plan_step import PlanStep
from src.agents.planning.goal import Goal


class ExecutionPlan:
    """
    Represents a complete execution plan
    generated by an intelligent agent.

    A plan contains ordered execution steps
    based on an agent goal.
    """


    def __init__(
        self,
        objective: Optional[str] = None,
        steps: Optional[List[PlanStep]] = None,
        metadata: Optional[Dict[str, Any]] = None,
        goal: Optional[Goal] = None
    ):

        self.goal = goal

        self.objective = (
            goal.objective
            if goal
            else objective
        )

        self.steps = (
            steps
            if steps
            else []
        )

        self.metadata = (
            metadata
            if metadata
            else {}
        )


    def add_step(
        self,
        step: PlanStep
    ):
        """
        Add a new execution step
        to the plan.
        """

        self.steps.append(
            step
        )


    def next_step(
        self
    ) -> Optional[PlanStep]:
        """
        Return the next pending step.
        """

        for step in self.steps:

            if step.status == "pending":

                return step


        return None


    def is_completed(
        self
    ) -> bool:
        """
        Check whether all steps
        were completed.
        """

        if not self.steps:

            return False


        return all(
            step.is_completed()
            for step in self.steps
        )


    def summary(
        self
    ) -> Dict[str, Any]:
        """
        Return execution summary.
        """

        return {

            "objective": self.objective,

            "goal": (
                self.goal.objective
                if self.goal
                else None
            ),

            "total_steps": len(
                self.steps
            ),

            "completed_steps": len(
                [
                    step
                    for step in self.steps
                    if step.status == "completed"
                ]
            ),

            "status": (
                "completed"
                if self.is_completed()
                else "in_progress"
            )

        }