from typing import Optional

from src.agents.planning.execution_plan import ExecutionPlan
from src.agents.planning.plan_step import PlanStep
from src.agents.reasoning.reasoning_result import ReasoningResult


class ExecutionPlanner:
    """
    Responsible for creating execution plans.

    The planner defines the sequence of actions
    required to execute an agent workflow.

    In V1.11 the planner starts consuming
    reasoning outputs generated by the
    ReasoningEngine.
    """

    def create_plan(
        self,
        question: str,
        reasoning_result: Optional[ReasoningResult] = None
    ) -> ExecutionPlan:
        """
        Create an execution plan.

        The planner can optionally use
        reasoning information to enrich
        the execution strategy.
        """

        plan = ExecutionPlan(
            objective=question
        )


        if reasoning_result:

            plan.metadata = {

                "reasoning": (
                    reasoning_result.reasoning
                ),

                "conclusion": (
                    reasoning_result.conclusion
                ),

                "confidence": (
                    reasoning_result.confidence
                ),

                "strategy": (
                    reasoning_result.strategy
                    if hasattr(
                        reasoning_result,
                        "strategy"
                    )
                    else "default"
                ),

                "required_capabilities": (
                    reasoning_result.required_capabilities
                    if hasattr(
                        reasoning_result,
                        "required_capabilities"
                    )
                    else []
                )

            }


        plan.add_step(
            PlanStep(
                step_id=1,
                action="route_request",
                description=(
                    "Select the best agent tool "
                    "for the request."
                )
            )
        )


        plan.add_step(
            PlanStep(
                step_id=2,
                action="execute_tool",
                description=(
                    "Execute selected tool."
                )
            )
        )


        plan.add_step(
            PlanStep(
                step_id=3,
                action="generate_response",
                description=(
                    "Prepare final response."
                )
            )
        )


        return plan