"""Reflection history service."""

from ..domain import ReflectionSummary


class ReflectionHistory:
    """Stores reflection summaries generated by the system."""

    def __init__(self) -> None:
        self._history: list[ReflectionSummary] = []

    def add(
        self,
        summary: ReflectionSummary,
    ) -> None:
        """Store a reflection summary."""
        self._history.append(summary)

    def all(self) -> list[ReflectionSummary]:
        """Return all stored reflection summaries."""
        return list(self._history)

    def latest(self) -> ReflectionSummary | None:
        """Return the most recent reflection summary."""
        if not self._history:
            return None

        return self._history[-1]

    def clear(self) -> None:
        """Clear the reflection history."""
        self._history.clear()

    @property
    def total_reflections(self) -> int:
        """Return the total number of stored reflections."""
        return len(self._history)