from pathlib import Path

import pandas as pd


class ProcessedDataLoader:
    """
    Loader responsible for loading processed datasets.

    Processed datasets are stored as parquet files
    generated by the DataPipeline.

    This loader does not transform data.
    It only provides access to prepared datasets.
    """


    def __init__(
        self,
        data_path="data/processed"
    ):

        self.data_path = Path(
            data_path
        )


    def load_parquet(
        self,
        filename,
        name=None
    ):
        """
        Loads a single parquet dataset.
        """

        file_path = (
            self.data_path /
            filename
        )


        if not file_path.exists():

            raise FileNotFoundError(
                f"Processed file not found: {file_path}"
            )


        dataframe = pd.read_parquet(
            file_path
        )


        dataset_name = (
            name
            if name
            else file_path.stem
        )


        return {
            "name": dataset_name,
            "dataframe": dataframe
        }



    def load_all(self):
        """
        Loads all processed datasets.

        Returns:
            Dictionary containing DataFrames.
        """


        if not self.data_path.exists():

            raise FileNotFoundError(
                f"Processed data directory not found: {self.data_path}"
            )


        datasets = {}


        for file in self.data_path.glob(
            "*.parquet"
        ):

            dataset_name = file.stem


            datasets[dataset_name] = (
                pd.read_parquet(file)
            )


        return datasets